package yandex

// DeviceType - https://yandex.ru/dev/dialogs/smart-home/doc/concepts/device-types.html
type DeviceType string

const (
	DeviceTypeCamera                 DeviceType = "devices.types.camera"
	DeviceTypeCooking                DeviceType = "devices.types.cooking"
	DeviceTypeCookingCoffeeMaker     DeviceType = "devices.types.cooking.coffee_maker"
	DeviceTypeCookingKettle          DeviceType = "devices.types.cooking.kettle"
	DeviceTypeCookingMulticooker     DeviceType = "devices.types.cooking.multicooker"
	DeviceTypeDishwasher             DeviceType = "devices.types.dishwasher"
	DeviceTypeHumidifier             DeviceType = "devices.types.humidifier"
	DeviceTypeIron                   DeviceType = "devices.types.iron"
	DeviceTypeLight                  DeviceType = "devices.types.light"
	DeviceTypeLightStrip             DeviceType = "devices.types.light.strip"
	DeviceTypeMediaDevice            DeviceType = "devices.types.media_device"
	DeviceTypeMediaDeviceReceiver    DeviceType = "devices.types.media_device.receiver"
	DeviceTypeMediaDeviceTV          DeviceType = "devices.types.media_device.tv"
	DeviceTypeMediaDeviceTVBox       DeviceType = "devices.types.media_device.tv_box"
	DeviceTypeOpenable               DeviceType = "devices.types.openable"
	DeviceTypeOpenableCurtain        DeviceType = "devices.types.openable.curtain"
	DeviceTypeOther                  DeviceType = "devices.types.other"
	DeviceTypePetDrinkingFountain    DeviceType = "devices.types.pet_drinking_fountain"
	DeviceTypePetFeeder              DeviceType = "devices.types.pet_feeder"
	DeviceTypePurifier               DeviceType = "devices.types.purifier"
	DeviceTypeSensor                 DeviceType = "devices.types.sensor"
	DeviceTypeSensorButton           DeviceType = "devices.types.sensor.button"
	DeviceTypeSensorClimate          DeviceType = "devices.types.sensor.climate"
	DeviceTypeSensorGas              DeviceType = "devices.types.sensor.gas"
	DeviceTypeSensorIllumination     DeviceType = "devices.types.sensor.illumination"
	DeviceTypeSensorMotion           DeviceType = "devices.types.sensor.motion"
	DeviceTypeSensorOpen             DeviceType = "devices.types.sensor.open"
	DeviceTypeSensorSmoke            DeviceType = "devices.types.sensor.smoke"
	DeviceTypeSensorVibration        DeviceType = "devices.types.sensor.vibration"
	DeviceTypeSensorWaterLeak        DeviceType = "devices.types.sensor.water_leak"
	DeviceTypeSmartMeter             DeviceType = "devices.types.smart_meter"
	DeviceTypeSmartMeterColdWater    DeviceType = "devices.types.smart_meter.cold_water"
	DeviceTypeSmartMeterElectricity  DeviceType = "devices.types.smart_meter.electricity"
	DeviceTypeSmartMeterGas          DeviceType = "devices.types.smart_meter.gas"
	DeviceTypeSmartMeterHeat         DeviceType = "devices.types.smart_meter.heat"
	DeviceTypeSmartMeterHotWater     DeviceType = "devices.types.smart_meter.hot_water"
	DeviceTypeSocket                 DeviceType = "devices.types.socket"
	DeviceTypeSwitch                 DeviceType = "devices.types.switch"
	DeviceTypeThermostat             DeviceType = "devices.types.thermostat"
	DeviceTypeDeviceTypeThermostatAC DeviceType = "devices.types.thermostat.ac"
	DeviceTypeVacuumCleaner          DeviceType = "devices.types.vacuum_cleaner"
	DeviceTypeWashingMachine         DeviceType = "devices.types.washing_machine"
)
